server:
  port: 8080


spring:
  profiles:
    active: @spring.active@  # 分区配置
  jackson:
    time-zone: GMT+8


log:
  path: D:/Users/admin/IdeaProjects/springBoot/zc-logs


---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/zc_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true
    username: root
    password:

  liquibase:
    change-log: classpath:db/changelog-master.yaml
    check-change-log-location: false

  ldap:
    userDnPatterns: uid={0},ou=People
    groupSearchBase: ou=GROUP
    url: ldap://172.168.1.119:389/dc=my-domain,dc=com


---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/zc_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true
    username: root
    password:

  liquibase:
    change-log: classpath:db/changelog-master-test.yaml
    check-change-log-location: false

  ldap:
    userDnPatterns: uid={0},ou=People
    groupSearchBase: ou=GROUP
    url: ldap://172.168.1.119:389/dc=my-domain,dc=com

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/zc_produce?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&createDatabaseIfNotExist=true
    username: root
    password:

  liquibase:
    change-log: classpath:db/changelog-master.yaml
    check-change-log-location: false

  ldap:
    userDnPatterns: uid={0},ou=People
    groupSearchBase: ou=GROUP
    url: ldap://172.168.1.119:389/dc=my-domain,dc=com

